version: '3'
services:
  php-simple-web:
    container_name: php-simple-web-staging
    build: ..
    ports:
      - "${STAGING_PORT}:80"
  database:
    container_name: database-staging
    image: mysql:latest
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=agileadvn
      - MYSQL_DATABASE=agileadvn
      - MYSQL_USER=agileadvn
      - MYSQL_PASSWORD=agileadvn
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ../mysql:/etc/mysql/conf.d
